print("Welcome to the band name generator.")
city = input("What's name of the city you grew up in?\n")
# print(city)
pet_name = input("What's your pet's name?\n")
# print(pet_name)
print("Your band name could be " +city+ " " + pet_name)
